npr_api.settings:
  type: config_entity
  label: 'NPR API settings'
  mapping:
    npr_api_api_key:
      type: text
      label: 'NPR API key'
    npr_api_production_url:
      type: text
      label: 'Production URL'
    npr_api_stage_url:
      type: text
      label: 'Staging URL'
